### ISSUE TITLE
Suggestion: a line for filename customization

### ISSUE THREAD

**Issue by SekoiaTree** [sorenrehkopf/custom-rick-roll#10]
In page creation, there should be a way to edit the name of the html file, because most news websites don't give their page the exact name of their title.

**Comment by sorenrehkopf** [comment]
Hey @SekoiaTree! This isn't a bad idea! I work on this site relatively infrequently as it was just a hobby project from a few years back, but next time I get around to making updates I'll look at adding this. 

If you'd like to fork and open a PR for the client-side changes for this though I could probably get around to making the server-side changes to accommodate it sooner than later. :+1:

**Comment by sorenrehkopf** [comment]
Hey @SekoiaTree! Finally got around to this. Committed a suggestion on the PR and merged. If you clear your cache you should see the pagename optional input at the bottom of the form now, and it will let you set the file name for the url if you want now. 

Thanks again!
