### ISSUE TITLE
It works now!

### ISSUE THREAD

**Issue by Landon6** [sorenrehkopf/custom-rick-roll#12]
I click create website and it doesn't work, im probably being stupid so please let me know.

**Comment by sorenrehkopf** [comment]
Hey @Landon6 thanks for letting me know! Could you give me your device and browser name and version? Everything seems to be working normally on the browsers and devices I usually test on. 

Also if there's any more specific details about what you're doing before experiencing the error that would be helpful.

Thanks!

**Comment by Awantje** [comment]
I also have this issue.
It redirects to localhost:3030
Chrome: 85.0.4183.121
Lenovo IdeaPad 500-15ISK

**Comment by sorenrehkopf** [comment]
Thanks for the details @Awantje . Can I clarify when you say it redirects you do you mean that you click the buttton to create and the page automatically takes you to localhost:3030 as if you clicked a link? Or is the url for the generated link `http://localhost:3030/index.html`?

**Comment by WathikAhmed** [comment]
Yeah dosent work for me either

sends me to: https://www.secretrickroll.com/

and then says:

This site can’t provide a secure connectionwww.secretrickroll.com sent an invalid response.

------------
I was able to load the actual rick roll link, just not the make your own link

**Comment by Landon6** [comment]
It works now, the issue i was having is my school chromebook probably blocked it or something, nothing on your end. Anyways thanks!
