### ISSUE TITLE
Kazoo Roll?

### ISSUE THREAD

**Issue by bc-185** [sorenrehkopf/custom-rick-roll#14]
I would like you to allow them to make a page that plays "Ofer Koren-Kazoo Zoo". They will have been "Kazoo Rolled". The link under is the "Kazoo Roll" video.
https://www.youtube-nocookie.com/embed/7m5NGjBidDU?autoplay=1&start=2

**Comment by sorenrehkopf** [comment]
Hey @bc-185!

Thanks for the suggestion! I have thought about a potential update where I would let people choose from other popular trolling videos, or enter their own. I don't have any immediate plans to do this, but I may get around to it eventually!

I'm going to close this issue but I'll keep it in mind for a possible future update. Thanks!

**Comment by bc-185** [comment]
That sounds interesting! I would also like to see the video above in the generator for "Kazoo Rolling" if you make the update.
