### ISSUE TITLE
you can see what it is

### ISSUE THREAD

**Issue by ghost** [sorenrehkopf/custom-rick-roll#15]
if your on one of these you can just ctrl + scroll to see whats behind or on mobile you can pinch your screen on safari

**Comment by sorenrehkopf** [comment]
Hey @theweewooman! 

That's a good point I had not thought of that... Personally I'm not too concerned about it as it's just an attempt to get them to unknowingly click through. If someone is suspicious and trying to see what's behind it for some reason then good for them they've avoided the rick roll! If they wanted they could also just open the browser console and delete the elements entirely.

I'm going to close this but if you would like to figure out a way to prevent that then feel free to reply with a solution and I'd be happy to implement it next time I get around to making updates. Either way thanks for reporting!
