### ISSUE TITLE
users can tab complete to pause the player etc

### ISSUE THREAD

**Issue by sophuric** [sorenrehkopf/custom-rick-roll#17]
title

**Comment by sorenrehkopf** [comment]
Hey @mekb-turtle! 

I'm not entirely sure what the issue being described here is, but if it's that people still have control over the video with keyboard controlls, then I'm not really concerned about it tbh. This is just a for-fun gag so the main goal is that people can't _easily_ stop the video as they normally would, not to absolutely ensure that they can't stop it by any means. They can of course always just close the page if they want. 

Gonna close this. If I'm misunderstanding what you're describing here then feel free to re-open.
