### ISSUE TITLE
Cookie accept screen is outdated

### ISSUE THREAD

**Issue by aolgeirson** [sorenrehkopf/custom-rick-roll#18]
Changing the cookie accept page to a more modern MSN homepage would be helpful. Seeing a MSN page from last year might set some ret flags for veiwers.

**Comment by sorenrehkopf** [comment]
Hey @Changeme-NUL! Good point. I'll look around and see if I can find something more current and / or less identifiable.

Gonna close this but thanks for pointing it out! Had not occurred to me.
