### ISSUE TITLE
Just some information for ya

### ISSUE THREAD

**Issue by zombiestruck** [sorenrehkopf/custom-rick-roll#21]
Tomorrow times is being detected as a malicious URL by multiple AVs, you have made it!

**Comment by sorenrehkopf** [comment]
If rick rolling is malicious then I don't wanna be non-malicious lol.

Not entirely surprised based on traffic. I'll swap it out for a fresh one eventually but based on traffic it still seems to be getting the most hits so probably not a big deal for now. 

Thanks for the heads up though! I'll keep an eye on it.
