### ISSUE TITLE
Can pause with key shortcut on computer

### ISSUE THREAD

**Issue by MattiDeP** [sorenrehkopf/custom-rick-roll#23]
hello, i just discovered that i can pause the video using the function key on my laptop. Is it fixable or not?

https://user-images.githubusercontent.com/79059837/107887751-8bc07700-6f08-11eb-8c3d-5cd36d92d3a4.mp4

**Comment by dj-v3rsa** [comment]
No

**Comment by sorenrehkopf** [comment]
Hey @MattiDeP, I am not sure whether that is preventable or not. @awesome-coder-d seems to think it's not. In either case I'm not really that concerned about it. People will always be able to find some way to pause the video if they really want. Finding a 100% foolproof way to force people to watch the entire video isn't really the point of this project. It's just a for-fun gag, and they can always close the page if they really don't want to watch.

Thanks for reporting though!
