### ISSUE TITLE
Video is able to be stopped

### ISSUE THREAD

**Issue by ihaveanaccount** [sorenrehkopf/custom-rick-roll#26]
![image](https://user-images.githubusercontent.com/74076340/112859820-33d96c00-9081-11eb-8734-9471c460e953.png)
here i just have to delete the vid-blocker element then the video can be stopped shown in attached 2
![image](https://user-images.githubusercontent.com/74076340/112859919-51a6d100-9081-11eb-92d5-b7ec795705e8.png)

**Comment by zaourzag** [comment]
This is not supposed to be done  as you can read under the video is this:"no controls under this video, you have no control" blaba that is the joke

**Comment by echomusician** [comment]
you normally wont do that

also thats not really an issue as you have been rickrolled either way :D

**Comment by leewp14** [comment]
it seems like you have just unlocked an achievement, congrats! lol

**Comment by sorenrehkopf** [comment]
Yeah @D3fa1t1 and @leewp14 are both right. I'm not trying to like override chrome dev tools to not let people delete elements. The whole vid blocker thing is just a detail anyway. If the video plays then they've been rick rolled.

If I get more complaints about being able to stop the video somehow I'm just gonna delete that text that says that. It's not the point.

**Comment by yeetus-maximus** [comment]
Kook
