### ISSUE TITLE
Help with building

### ISSUE THREAD

**Issue by zaourzag** [sorenrehkopf/custom-rick-roll#27]
How to build

**Comment by zaourzag** [comment]
The problem right now is: I've successfully build bundle.js and tested it via npx start. But when I try to make a page it's like nope f you ima return your html file instead. I've changed the URLs. And I've also tried nginx with the index.html to no hope I hope you can help me with my problem as the site can be unreliable at times, Zakaria Aourzag 
Mentions: @sorenrehkopf

**Comment by hungl6844** [comment]
seriously....? I mean, I'll help, but why?

**Comment by sorenrehkopf** [comment]
Hey @zaourzag! So this repo is just the client for the app. This repo itself doesn't actually create the pages it just interfaces with a serverside api that does. That api is in another repo and you'd have to build out your own api to build the pages if you wanted a fully functioning version of the site for yourself. 

If you really want to keep tinkering around with it I won't dissuade you, but to be totally upfront this is very much a hobby project for me that I have very limited time dedicated to so I can't really commit to supporting other developers very much. 

Hope that helps clarify things, and sorry to not be of more assistance.

**Comment by zaourzag** [comment]
> Hey @zaourzag! So this repo is just the client for the app. This repo itself doesn't actually create the pages it just interfaces with a serverside api that does. That api is in another repo and you'd have to build out your own api to build the pages if you wanted a fully functioning version of the site for yourself.
> 
> If you really want to keep tinkering around with it I won't dissuade you, but to be totally upfront this is very much a hobby project for me that I have very limited time dedicated to so I can't really commit to supporting other developers very much.
> 
> Hope that helps clarify things, and sorry to not be of more assistance.

That clarifies alot actually! So the api is in another repo? Is it a private one? Just wondering rn

**Comment by sorenrehkopf** [comment]
Yeah I have it in a private repo just for a little bit of security since it contains the code that actually writes the files. 

If it helps you could really use whatever templating engine you wanted if you were to build out your own version.

Can I ask what you're trying to run this project locally for? Just curious.

**Comment by zaourzag** [comment]
I think it as because the servers usually  dont respond or take reallyyyyyyy long to load. making it kinda to unstable to use. Also the api sometimes  just times out thus making no custom page

**Comment by sorenrehkopf** [comment]
Mmm yup! When you opened this issue there were some problems going on with scale that I wasn't aware of. They should be resolved now. 

I'm gonna go ahead and close this issue since there's nothing actionable here for me now. Feel free to open a separate issue for slowness if you see it again in the future!

**Comment by zaourzag** [comment]
Hey @sorenrehkopf, just coming back to this. What exactly do you use on the backend? Express+pug? I'm curious to know what you use!
