### ISSUE TITLE
My link not working check it plz

### ISSUE THREAD

**Issue by Emma-coder67** [sorenrehkopf/custom-rick-roll#28]
https://www.theraleighregister.com/e32035.html

**Comment by Imagine-YT** [comment]
Are you trying to rickroll us?

**Comment by Emma-coder67** [comment]
no

**Comment by Emma-coder67** [comment]
As long as the trolls are still trolling, we will never stop Rick rolling

**Comment by zombiestruck** [comment]
Can confirm the link is not working - issue needs to be reopened.
