### ISSUE TITLE
If you scroll up mobile you can see the roll

### ISSUE THREAD

**Issue by ghost** [sorenrehkopf/custom-rick-roll#33]

**Comment by superintendent2521** [comment]
A way to fix this is  by making the Accept cookies and Roll two diffrent pages,

**Comment by sorenrehkopf** [comment]
I am unable to reproduce on my own devices. If you're able to repro reliably on your device feel free to open a pr with a fix! I'm going to close this for now though. I can reopen if it seems to be a widespread issue.
