### ISSUE TITLE
fix the markdown

### ISSUE THREAD

**Issue by TheTechRobo** [sorenrehkopf/custom-rick-roll#7]
Just change 

```
#Custom rick roll
```

to 

```
# Custom rick roll
```

and it works better

**Comment by sorenrehkopf** [comment]
Haha good point. I'll remember to do this next time I make updates. Thanks!

**Comment by sorenrehkopf** [comment]
Resolved in https://github.com/sorenrehkopf/custom-rick-roll/pull/13 thanks @TheTechRobo!
