### ISSUE TITLE
Suggestion: Add a toggle for the cookies message

### ISSUE THREAD

**Issue by SekoiaTree** [sorenrehkopf/custom-rick-roll#9]
As the title says: during creation, there should be a toggle for the cookies message that displays when you load the page originally.

**Comment by sorenrehkopf** [comment]
Hey again @SekoiaTree As mentioned on [this issue](https://github.com/sorenrehkopf/custom-rick-roll/issues/1#issuecomment-674660576) Unfortunately the accept cookies message is necessary in order to "autoplay" the video at all. Would be nice though! Thanks for the suggestion.

**Comment by SekoiaTree** [comment]
Fair enough!
